FIND_PACKAGE(PkgConfig)
PKG_CHECK_MODULES(PC_SDL2 QUIET sdl2)

FIND_LIBRARY(SDL2_LIBRARIES
    NAMES SDL2
    HINTS ${PC_SDL2_LIBDIR}
          ${PC_SDL2_LIBRARY_DIRS}
)

FIND_PATH(SDL2_INCLUDE_DIR
    NAMES SDL2/SDL.h
    HINTS ${PC_SDL2_INCLUDEDIR}
          ${PC_SDL2_INCLUDE_DIRS}
)

SET(SDL2_INCLUDE_DIRS ${SDL2_INCLUDE_DIR})

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(SDL2 REQUIRED_VARS SDL2_INCLUDE_DIRS SDL2_LIBRARIES)
